#!/usr/bin/env bash

# # build
#
# Build the site, which is static.
#
# Assumes the following are checked out as siblings of the current repository:
# - <https://github.com/yawnoc/mahjong-scorer>
# - <https://github.com/conway-markdown/conway-markdown>

latest_date=$(grep -P '^[0-9]{4}-[0-9]{2}-[0-9]{2}' ./scores/scores.txt | tail -1)

python3 ../mahjong-scorer/mahjongscore.py ./scores/scores.txt
python3 ../mahjong-scorer/mahjongscore.py ./scores/scores.txt --from $latest_date
python3 ./res/scoring.py
python3 ../conway-markdown/cmd.py
python3 ./res/sitemap.py
